# Compiler Design Module 2 Exhaustive Content (10 Topics Complete)
# Neuroscience framework: Understand -> Visualize -> Connect -> Recall -> Apply -> Exam-Important Questions

CD_M2_EXHAUSTIVE = r"""
<div class="toc-box">
  <div class="toc-title"><i class="fa-solid fa-list-check"></i> Module II: Syntax Analysis — Complete 10-Topic Syllabus Tracker</div>
  <div class="toc-grid">
    <div><strong>Topic 1:</strong> Introduction to Syntax Analysis & CFG Grammars</div>
    <div><strong>Topic 2:</strong> Grammar Rewriting (Left Recursion & Left Factoring)</div>
    <div><strong>Topic 3:</strong> Recursive Top-Down Parsers (Recursive Descent & Backtracking)</div>
    <div><strong>Topic 4:</strong> Non-Recursive Top-Down Parsers (Predictive Stack & Buffer)</div>
    <div><strong>Topic 5:</strong> Design of LL(1) Parser (FIRST & FOLLOW Inductive Rules)</div>
    <div><strong>Topic 6:</strong> Bottom-Up Parsers (Shift, Reduce & Handle Pruning)</div>
    <div><strong>Topic 7:</strong> Variants of LR Parsers (LR(0), SLR(1), CLR(1), LALR(1))</div>
    <div><strong>Topic 8:</strong> Handling Parsing Conflicts (Shift-Reduce & Reduce-Reduce)</div>
    <div><strong>Topic 9:</strong> Detection of Syntax Errors (Panic-Mode & Phrase-Level)</div>
    <div><strong>Topic 10:</strong> Reporting of Syntax Errors & Informative Diagnostics</div>
  </div>
</div>

<h2 class="section-title">Topic 1: Introduction to Syntax Analysis & CFG Grammars</h2>
<p>
  <strong>Syntax Analysis (Parsing)</strong> takes the stream of tokens generated by the lexical analyzer and verifies whether the token sequence conforms to the syntactic rules of the language defined by a <strong>Context-Free Grammar (CFG)</strong> $G = (V, T, P, S)$.
</p>

<h2 class="section-title">Topic 2: Grammar Rewriting Transformations</h2>

<h3 class="subsection-title">1. Immediate Left Recursion Elimination:</h3>
<p>For grammar production $A \rightarrow A \alpha_1 \mid A \alpha_2 \mid \dots \mid \beta_1 \mid \beta_2$ where no $\beta_i$ starts with $A$:</p>
<div class="formula-card">
  $$A \rightarrow \beta_1 A' \mid \beta_2 A' \mid \dots$$
  $$A' \rightarrow \alpha_1 A' \mid \alpha_2 A' \mid \dots \mid \epsilon$$
</div>

<h3 class="subsection-title">2. Left Factoring:</h3>
<p>Delays the parsing decision when multiple productions share a common prefix $\alpha$:</p>
<div class="formula-card">
  $$A \rightarrow \alpha \beta_1 \mid \alpha \beta_2 \implies A \rightarrow \alpha A', \quad A' \rightarrow \beta_1 \mid \beta_2$$
</div>

<h2 class="section-title">Topic 3 & 4: Top-Down Parsers (Recursive vs. Non-Recursive)</h2>

<table class="custom-table">
  <thead>
    <tr>
      <th style="width: 25%;">Top-Down Parser Type</th>
      <th style="width: 45%;">Internal Architecture & Mechanism</th>
      <th>Key Limitations & Mitigations</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Recursive Descent Parser</strong></td>
      <td>Executes a set of mutually recursive C/Java functions where each non-terminal corresponds to a procedure.</td>
      <td>Cannot directly handle left recursion (causes infinite loop); requires backtracking without predictive lookahead.</td>
    </tr>
    <tr>
      <td><strong>Non-Recursive Predictive Parser</strong></td>
      <td>Uses an explicit Parser Stack, an Input Buffer with endmarker `$`, and a 2D parsing table $M[A, a]$.</td>
      <td>Requires grammar strictly to be $LL(1)$ without conflicts.</td>
    </tr>
  </tbody>
</table>

<h2 class="section-title">Topic 5: Design of LL(1) Parsers (FIRST & FOLLOW Inductive Formulations)</h2>

<div class="formula-card">
  <strong>Inductive Rules for $\text{FIRST}(\alpha)$:</strong>
  1. If $X$ is a terminal, $\text{FIRST}(X) = \{X\}$.
  2. If $X \rightarrow \epsilon$, then $\epsilon \in \text{FIRST}(X)$.
  3. If $X \rightarrow Y_1 Y_2 \dots Y_k$, add all non-$\epsilon$ symbols of $\text{FIRST}(Y_1)$ to $\text{FIRST}(X)$. If $\epsilon \in \text{FIRST}(Y_1)$, add $\text{FIRST}(Y_2)$, and so on. If all $Y_i \Rightarrow^* \epsilon$, add $\epsilon \in \text{FIRST}(X)$.
</div>

<div class="formula-card">
  <strong>Inductive Rules for $\text{FOLLOW}(A)$:</strong>
  1. For start symbol $S$, place endmarker $\$$ into $\text{FOLLOW}(S)$.
  2. For production $A \rightarrow \alpha B \beta$, add $(\text{FIRST}(\beta) \setminus \{\epsilon\})$ into $\text{FOLLOW}(B)$.
  3. For production $A \rightarrow \alpha B$ or $A \rightarrow \alpha B \beta$ where $\epsilon \in \text{FIRST}(\beta)$, add all elements of $\text{FOLLOW}(A)$ into $\text{FOLLOW}(B)$.
</div>

<div class="callout callout-warning">
  <div class="callout-title">Condition for Grammar to be LL(1)</div>
  A grammar $G$ is $LL(1)$ if and only if for every pair of productions $A \rightarrow \alpha \mid \beta$:
  1. $\text{FIRST}(\alpha) \cap \text{FIRST}(\beta) = \emptyset$
  2. If $\epsilon \in \text{FIRST}(\beta)$, then $\text{FIRST}(\alpha) \cap \text{FOLLOW}(A) = \emptyset$.
</div>

<h2 class="section-title">Topic 6 & 7: Bottom-Up Parsers & LR Variants Hierarchy</h2>

<p>
  <strong>Bottom-Up Parsers</strong> construct the parse tree starting from the terminal leaves at the bottom and reducing back to the start symbol $S$ at the root (Rightmost Derivation in Reverse):
</p>

<table class="custom-table">
  <thead>
    <tr>
      <th style="width: 18%;">LR Family</th>
      <th style="width: 25%;">Item Representation</th>
      <th style="width: 25%;">Reduction Decision Rule</th>
      <th>State Complexity & Relative Power</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>1. LR(0)</strong></td>
      <td>$[A \rightarrow \alpha \cdot \beta]$</td>
      <td>Reduce unconditionally in entire row for all input tokens.</td>
      <td>Smallest table; least powerful. Prone to conflicts.</td>
    </tr>
    <tr>
      <td><strong>2. SLR(1)</strong></td>
      <td>$[A \rightarrow \alpha \cdot \beta]$ (Same as LR(0))</td>
      <td>Reduce only on input tokens $a \in \text{FOLLOW}(A)$.</td>
      <td>Same number of states as LR(0); eliminates many conflicts.</td>
    </tr>
    <tr>
      <td><strong>3. CLR(1)</strong></td>
      <td>$[A \rightarrow \alpha \cdot \beta, \ a]$ (With 1 Lookahead)</td>
      <td>Reduce only on exact propagated lookahead token $a$.</td>
      <td>Most powerful; massive number of states (thousands).</td>
    </tr>
    <tr>
      <td><strong>4. LALR(1)</strong></td>
      <td>Merged CLR(1) items with identical cores.</td>
      <td>Reduce on merged lookahead sets.</td>
      <td>Same state count as SLR(1) with near CLR(1) parsing power. Used in Yacc / Bison.</td>
    </tr>
  </tbody>
</table>

<h2 class="section-title">Topic 8 – 10: Handling Parsing Conflicts & Error Recovery</h2>

<h3 class="subsection-title">1. Parsing Conflicts:</h3>
<ul>
  <li><strong>Shift-Reduce (S-R) Conflict:</strong> The parser cannot decide whether to shift the incoming token or reduce the stack handle (e.g., the classic Dangling Else ambiguity).</li>
  <li><strong>Reduce-Reduce (R-R) Conflict:</strong> The parser has two distinct valid reduction rules available for the same lookahead token, indicating deep grammar ambiguity.</li>
</ul>

<h3 class="subsection-title">2. Syntax Error Recovery Techniques:</h3>
<ol>
  <li><strong>Panic-Mode Recovery:</strong> Parser discards input tokens one by one until a designated <em>synchronizing token</em> (e.g., `;` or `}`) is found, then pops non-terminals to resume parsing.</li>
  <li><strong>Phrase-Level Recovery:</strong> Parser performs local correction on the remaining input (e.g., inserting a missing semicolon or replacing a comma with a semicolon).</li>
  <li><strong>Error Productions:</strong> Grammar is augmented with explicit rules that anticipate common syntactic mistakes (e.g., `5x` instead of `5 * x`).</li>
</ol>

<h2 class="section-title">🧠 M2 Active Recall & Exam-Important Question Bank</h2>

<div class="qa-card">
  <div class="qa-q">Q1. Given grammar $S \rightarrow ( L ) \mid a$ and $L \rightarrow L, S \mid S$, eliminate left recursion and compute FIRST and FOLLOW. (8 Marks)</div>
  <div class="qa-a">
    1. <strong>Eliminate Left Recursion on $L$:</strong><br>
       $L \rightarrow S L'$<br>
       $L' \rightarrow , S L' \mid \epsilon$<br>
    2. <strong>Compute FIRST Sets:</strong><br>
       $\text{FIRST}(S) = \{(, a\}$<br>
       $\text{FIRST}(L) = \text{FIRST}(S) = \{(, a\}$<br>
       $\text{FIRST}(L') = \{,, \epsilon\}$<br>
    3. <strong>Compute FOLLOW Sets:</strong><br>
       $\text{FOLLOW}(S) = \{\$, ), ,\}$<br>
       $\text{FOLLOW}(L) = \{)\}$<br>
       $\text{FOLLOW}(L') = \text{FOLLOW}(L) = \{)\}$
  </div>
</div>
"""
