# Data Mining Module 4 Exhaustive Content (7 Topics Complete)
# Neuroscience framework: Understand -> Visualize -> Connect -> Recall -> Apply -> Exam-Important Questions & [UPLOADED PYQ]

DM_M4_EXHAUSTIVE = r"""
<div class="toc-box">
  <div class="toc-title"><i class="fa-solid fa-list-check"></i> Module IV: Frequent Pattern & Association Rule Mining — Complete 7-Topic Tracker</div>
  <div class="toc-grid">
    <div><strong>Topic 30:</strong> Basic Concepts of Frequent Pattern Mining</div>
    <div><strong>Topic 31:</strong> Association Rules (Support & Confidence Metrics)</div>
    <div><strong>Topic 32:</strong> Correlation Measures (Lift & Chi-Square Analysis) [UPLOADED PYQ]</div>
    <div><strong>Topic 33:</strong> Frequent Itemset Mining Methods Overview</div>
    <div><strong>Topic 34:</strong> The Apriori Algorithm (Join, Prune & Improvements) [UPLOADED PYQ]</div>
    <div><strong>Topic 35:</strong> The FP-Growth Algorithm (FP-Tree Construction & Mining) [UPLOADED PYQ]</div>
    <div><strong>Topic 36:</strong> Interesting Pattern Evaluation Measures (S-C-L Triad)</div>
  </div>
</div>

<h2 class="section-title">Topic 30 & 31: Association Rule Mining Formulations</h2>

<div class="formula-card">
  <strong>1. Support and Confidence Formulations for Rule $A \implies B$:</strong>
  $$\text{Support}(A \implies B) = P(A \cup B) = \frac{\text{Count}(A \cup B)}{|D|}$$
  $$\text{Confidence}(A \implies B) = P(B \mid A) = \frac{\text{Support}(A \cup B)}{\text{Support}(A)} = \frac{\text{Count}(A \cup B)}{\text{Count}(A)}$$
  A rule is <strong>Strong</strong> if $\text{Support} \ge \text{min\_sup}$ and $\text{Confidence} \ge \text{min\_conf}$.
</div>

<h2 class="section-title">Topic 32: Correlation Measures & The Lift Metric [UPLOADED PYQ]</h2>

<div class="formula-card">
  <strong>Lift Correlation Formula [UPLOADED PYQ — IT426 Mid]:</strong>
  $$\text{Lift}(A \implies B) = \frac{P(A \cup B)}{P(A) \cdot P(B)} = \frac{\text{Confidence}(A \implies B)}{\text{Support}(B)}$$
  <ul>
    <li><strong>$\text{Lift} > 1$:</strong> Positive correlation ($A$ and $B$ occur together more frequently than expected by chance).</li>
    <li><strong>$\text{Lift} = 1$:</strong> Statistical independence (no correlation between $A$ and $B$).</li>
    <li><strong>$\text{Lift} < 1$:</strong> Negative correlation (the presence of $A$ discourages the occurrence of $B$).</li>
  </ul>
</div>

<h2 class="section-title">Topic 34: The Apriori Algorithm (Join & Prune Steps) [UPLOADED PYQ]</h2>

<div class="callout callout-warning">
  <div class="callout-title">The Apriori Property & Pruning Theorem (Agrawal & Srikant, 1994)</div>
  <p><strong>Apriori Invariant:</strong> All non-empty subsets of a frequent itemset must also be frequent.</p>
  <p><strong>Anti-Monotonicity Pruning Rule:</strong> If an itemset is infrequent, all of its supersets are guaranteed to be infrequent and can be immediately pruned without scanning the database!</p>
  <ol>
    <li><strong>Join Step:</strong> $C_k$ candidate itemsets are generated by joining $L_{k-1}$ with itself ($L_{k-1} \bowtie L_{k-1}$).</li>
    <li><strong>Prune Step:</strong> Any candidate $c \in C_k$ is deleted if any of its $(k-1)$-subsets is not present in $L_{k-1}$.</li>
  </ol>
</div>

<h2 class="section-title">Topic 35: The FP-Growth Algorithm [UPLOADED PYQ]</h2>

<p>
  <strong>FP-Growth (Frequent Pattern Growth)</strong> overcomes the major computational bottlenecks of Apriori (repeated database scans and massive candidate generation) by constructing a compact prefix-tree structure called the <strong>FP-Tree</strong>.
</p>

<div class="worked-box">
  <div class="worked-title">🏛️ [UPLOADED PYQ — IT335 End] Full Solved Numerical: FP-Growth on Transaction Database ($\text{min\_sup} = 60\% = 3 \text{ out of } 5$)</div>
  <p><strong>Given 5 Transactions:</strong></p>
  <table class="custom-table">
    <thead><tr><th>TID</th><th>Items Purchased</th><th>Ordered Frequent Items ($\text{Support} \ge 3$)</th></tr></thead>
    <tbody>
      <tr><td>10</td><td>Beer, Nuts, Diapers</td><td>$\langle \text{Nuts}:4, \text{Beer}:4, \text{Diapers}:4 \rangle$</td></tr>
      <tr><td>20</td><td>Beer, Coffee, Diapers, Nuts</td><td>$\langle \text{Nuts}:4, \text{Beer}:4, \text{Diapers}:4 \rangle$ (Coffee dropped)</td></tr>
      <tr><td>30</td><td>Beer, Diapers, Eggs</td><td>$\langle \text{Beer}:4, \text{Diapers}:4, \text{Eggs}:3 \rangle$</td></tr>
      <tr><td>40</td><td>Beer, Nuts, Eggs, Milk</td><td>$\langle \text{Nuts}:4, \text{Beer}:4, \text{Eggs}:3 \rangle$ (Milk dropped)</td></tr>
      <tr><td>50</td><td>Nuts, Coffee, Diapers, Eggs, Milk</td><td>$\langle \text{Nuts}:4, \text{Diapers}:4, \text{Eggs}:3 \rangle$</td></tr>
    </tbody>
  </table>

  <p><strong>Step 1: Frequent 1-Itemsets:</strong> $\{\text{Nuts}:4, \text{Beer}:4, \text{Diapers}:4, \text{Eggs}:3\}$. Frequency Order: $\text{Nuts} \rightarrow \text{Beer} \rightarrow \text{Diapers} \rightarrow \text{Eggs}$.</p>
  <p><strong>Step 2: Mining Conditional Pattern Bases from Bottom of Header Table:</strong></p>
  <ul>
    <li><strong>Item `Eggs`:</strong> Conditional Pattern Base: $\{\langle \text{Beer}, \text{Diapers}: 1 \rangle, \langle \text{Nuts}, \text{Beer}: 1 \rangle, \langle \text{Nuts}, \text{Diapers}: 1 \rangle\}$. Conditional FP-Tree: $\emptyset$ (No item has $\text{support} \ge 3$). Frequent Itemset: $\{\text{Eggs}:3\}$.</li>
    <li><strong>Item `Diapers`:</strong> Conditional Pattern Base: $\{\langle \text{Nuts}, \text{Beer}: 2 \rangle, \langle \text{Beer}: 1 \rangle, \langle \text{Nuts}: 1 \rangle\}$. Conditional FP-Tree: $\langle \text{Nuts}:3, \text{Beer}:3 \rangle$. Frequent Itemsets: $\{\text{Diapers, Nuts}:3, \text{Diapers, Beer}:3\}$.</li>
    <li><strong>Item `Beer`:</strong> Conditional Pattern Base: $\{\langle \text{Nuts}:3 \rangle\}$. Conditional FP-Tree: $\langle \text{Nuts}:3 \rangle$. Frequent Itemset: $\{\text{Beer, Nuts}:3\}$.</li>
  </ul>
</div>

<h2 class="section-title">🧠 M4 Active Recall & Exam Questions [UPLOADED PYQ]</h2>

<div class="qa-card">
  <div class="qa-q">Q1. [UPLOADED PYQ — IT426 Mid] Compare the significance of Support and Confidence in association analysis. Why is Lift necessary? (8 Marks)</div>
  <div class="qa-a">
    - <strong>Support:</strong> Measures how frequently an itemset appears across the entire dataset ($P(A \cup B)$). It filters out statistically insignificant random noise.<br>
    - <strong>Confidence:</strong> Measures the conditional reliability of the inference rule ($P(B \mid A)$). High confidence means $B$ is likely when $A$ occurs.<br>
    - <strong>Why Lift is Necessary:</strong> Support and Confidence alone can be deceptive. For example, if 90% of all customers buy Tea ($P(\text{Tea})=0.9$) and rule `Coffee => Tea` has 80% confidence, Coffee actually <em>decreases</em> the likelihood of buying Tea! Lift computes $\frac{0.80}{0.90} = 0.89 < 1$, exposing the negative correlation that Confidence hid.
  </div>
</div>
"""
