#!/usr/bin/env python3
"""
Expands all Artificial Intelligence module contents with deep university textbook sections,
algorithm execution traces, and worked mathematical derivations to ensure 10-14 pages per module!
"""

import os

AI_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "artificial-intelligence"))

# Extra depth for AI M1
M1_EXTRA = r"""
<h2 class="section-title">Topic 7.2: In-Depth PEAS Design & State-Space Environment Modeling</h2>

<p>
  When architecting intelligent agent systems for enterprise and industrial automation, formal environmental modeling prevents catastrophic policy failures:
</p>

<table class="custom-table">
  <thead>
    <tr>
      <th style="width: 20%;">Enterprise Domain</th>
      <th style="width: 25%;">Percept Space & Sensor Hardware</th>
      <th style="width: 25%;">Action Space & Actuation</th>
      <th>State-Space Complexity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>High-Frequency Algorithmic Trading</strong></td>
      <td>L2/L3 order book feeds, trade tick streams, macroeconomic news NLP embeddings, latency telemetry.</td>
      <td>Limit buy/sell orders, cancel order, market orders, currency hedges.</td>
      <td>Continuous time, high-dimensional stochastic state space with adversarial market makers ($>10^9$ events/sec).</td>
    </tr>
    <tr>
      <td><strong>Automated Container Terminal (Port)</strong></td>
      <td>DGPS positioning, LiDAR collision arrays, optical container code scanners, ship manifest database.</td>
      <td>Gantry crane hoist/trolley motors, automated guided vehicles (AGV) throttle/steering.</td>
      <td>Hybrid discrete-continuous, dynamic multi-agent scheduling with hard real-time collision avoidance.</td>
    </tr>
    <tr>
      <td><strong>Smart Electrical Power Grid (SCADA)</strong></td>
      <td>Phasor measurement units (PMU), substation voltage/frequency telemetry, weather forecasts, solar/wind yields.</td>
      <td>Switchgear breakers, transformer tap changers, battery storage charge/discharge cycles.</td>
      <td>Large-scale continuous non-linear differential equation dynamics under extreme stochastic supply/demand shocks.</td>
    </tr>
  </tbody>
</table>

<div class="worked-box">
  <div class="worked-title">🏛️ Step-by-Step Solved Problem: Agent Utility Function Design under Multi-Objective Trade-offs</div>
  <p>An autonomous delivery drone must deliver medical supplies between hospitals. The system has three competing objectives:</p>
  <ul>
    <li>Delivery Time $T \in [10, 60]\text{ minutes}$ (Weight $w_1 = 0.50$, Target $T_{\text{target}} = 15\text{ min}$)</li>
    <li>Battery Energy Consumed $E \in [100, 500]\text{ Wh}$ (Weight $w_2 = 0.30$, Max Capacity $E_{\text{max}} = 500\text{ Wh}$)</li>
    <li>Flight Risk Factor $R \in [0.0, 1.0]$ over populated areas (Weight $w_3 = 0.20$)</li>
  </ul>
  <p><strong>Scalar Multi-Attribute Utility Function:</strong></p>
  $$\mathbf{U(T, E, R) = 100 \times \left[ 0.50 \cdot \max\left(0, 1 - \frac{T - 15}{45}\right) + 0.30 \cdot \left(1 - \frac{E}{500}\right) + 0.20 \cdot (1 - R) \right]}$$
  <p><em>Optimal Trajectory Selection:</em> A utility-based agent evaluates all candidate path plans $P_1, P_2, P_3$ generated by its search engine and executes the trajectory that maximizes expected scalar utility $\mathbb{E}[U]$!</p>
</div>

<div class="qa-card">
  <div class="qa-q">Q5. Explain the Subsumption Architecture proposed by Rodney Brooks. How does it contrast with Classical Symbolic AI? (8 Marks)</div>
  <div class="qa-a">
    • <strong>Classical Symbolic AI:</strong> Relies on a centralized "Sense-Plan-Act" pipeline with explicit symbolic internal world models.<br>
    • <strong>Subsumption Architecture (Behavior-Based AI):</strong> Eliminates central representations ("The world is its own best model"). The system is built from parallel, asynchronous, reactive behavioral layers (e.g. Layer 0: Avoid Obstacles; Layer 1: Wander; Layer 2: Explore). Higher layers can <em>suppress</em> inputs or <em>subsume</em> outputs of lower layers, achieving robust physical reactivity in dynamic environments without computationally prohibitive planning bottlenecks!
  </div>
</div>
"""

# Extra depth for AI M2
M2_EXTRA = r"""
<h2 class="section-title">Topic 13.2: Comprehensive Heuristic Design, Relaxation & Constraint Satisfaction</h2>

<div class="formula-card">
  <strong>Heuristic Dominance & Effective Branching Factor ($b^*$):</strong>
  If for two admissible heuristics $h_1, h_2$, we have $h_2(n) \ge h_1(n)$ for all nodes $n$, then $h_2$ <strong>dominates</strong> $h_1$. Dominance directly guarantees that $A^*$ using $h_2$ will never expand more nodes than $A^*$ using $h_1$!
  $$\mathbf{N + 1 = 1 + b^* + (b^*)^2 + \dots + (b^*)^d = \frac{(b^*)^{d+1} - 1}{b^* - 1}}$$
</div>

<div class="worked-box">
  <div class="worked-title">🏛️ Step-by-Step Solved Problem: Constructing Relaxed Problem Heuristics for the 8-Puzzle</div>
  <p>The rules of the 8-puzzle restrict a tile to move from square $A$ to square $B$ if and only if: (1) $A$ is adjacent to $B$, and (2) square $B$ is currently blank.</p>
  <ol>
    <li><strong>Relaxation 1 (Remove Condition 2):</strong> A tile can move to ANY adjacent square, even if occupied $\implies$ <strong>Manhattan Distance Heuristic:</strong>
      $$\mathbf{h_2(n) = \sum_{i=1}^8 \left( |x_i - x_{i,\text{goal}}| + |y_i - y_{i,\text{goal}}| \right)}$$
    </li>
    <li><strong>Relaxation 2 (Remove Conditions 1 & 2):</strong> A tile can move to ANY square directly $\implies$ <strong>Misplaced Tiles Heuristic:</strong>
      $$\mathbf{h_1(n) = \sum_{i=1}^8 \mathbb{I}(\text{Tile } i \text{ is not in goal position})}$$
    </li>
    <li><strong>Proof of Dominance:</strong> Since moving a tile to its destination takes at least 1 move if misplaced, and Manhattan distance is the sum of exact grid steps along orthogonal axes, we have $\mathbf{h_2(n) \ge h_1(n) \ge 0}$ for all states $n$. Thus, <strong>Manhattan Distance strictly dominates Misplaced Tiles!</strong></li>
  </ol>
</div>

<div class="worked-box">
  <div class="worked-title">🏛️ Solved Problem: Constraint Satisfaction Problem (CSP) Arc Consistency (AC-3 Algorithm)</div>
  <p>Consider Map Coloring of 3 regions $A, B, C$ connected in a triangle ($A-B, B-C, C-A$) with colors $\{\text{Red}, \text{Blue}\}$:</p>
  <ul>
    <li>Initial domains: $D(A) = \{\text{Red}, \text{Blue}\}, D(B) = \{\text{Red}, \text{Blue}\}, D(C) = \{\text{Red}, \text{Blue}\}$.</li>
    <li>Suppose $A$ is assigned $\text{Red} \implies D(A) = \{\text{Red}\}$.</li>
    <li><strong>AC-3 Queue Trace:</strong>
      <ol>
        <li>Arc $(B, A)$: For $B=\text{Red}$, no valid color in $D(A)$. Remove $\text{Red}$ from $D(B) \implies D(B) = \{\text{Blue}\}$.</li>
        <li>Arc $(C, A)$: Remove $\text{Red}$ from $D(C) \implies D(C) = \{\text{Blue}\}$.</li>
        <li>Arc $(C, B)$: For $C=\text{Blue}$, no valid color in $D(B)$ (since $D(B)=\{\text{Blue}\}$). Remove $\text{Blue}$ from $D(C) \implies \mathbf{D(C) = \emptyset \ (EMPTY DOMAIN!)}$.</li>
      </ol>
    </li>
    <li>$\mathbf{\text{AC-3 detects failure immediately, triggering backtrack without wasting full tree search!}}$</li>
  </ul>
</div>
"""

# Extra depth for AI M3
M3_EXTRA = r"""
<h2 class="section-title">Topic 22.2: Advanced Knowledge Engineering & Ontological Reasoning</h2>

<table class="custom-table">
  <thead>
    <tr>
      <th style="width: 25%;">Logic System</th>
      <th style="width: 35%;">Ontological Commitment (What exists in the world?)</th>
      <th>Epistemological Commitment (What can an agent believe?)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>Propositional Logic</strong></td>
      <td>Facts (Boolean true/false assertions).</td>
      <td>True, False, Unknown ($1, 0, ?$).</td>
    </tr>
    <tr>
      <td><strong>First-Order Logic (FOL)</strong></td>
      <td>Facts, Objects, Relations, Functions.</td>
      <td>True, False, Unknown.</td>
    </tr>
    <tr>
      <td><strong>Temporal Logic</strong></td>
      <td>Facts, Objects, Relations, Linear/Branching Time.</td>
      <td>True, False, Unknown across future/past paths.</td>
    </tr>
    <tr>
      <td><strong>Probability Theory</strong></td>
      <td>Facts with associated degree of belief.</td>
      <td>Real-valued scalar probability $P \in [0, 1]$.</td>
    </tr>
    <tr>
      <td><strong>Fuzzy Logic</strong></td>
      <td>Facts with vague/continuous degrees of truth.</td>
      <td>Degree of membership $\mu \in [0, 1]$.</td>
    </tr>
  </tbody>
</table>

<div class="worked-box">
  <div class="worked-title">🏛️ Complete Step-by-Step Solved Proof: The "Customs and Drug Smuggler" FOL Resolution</div>
  <p><strong>Axioms:</strong></p>
  <ol>
    <li>"Every customs official searches everyone who enters the country who is not a VIP."<br>
      $\forall x \forall y (\text{Official}(x) \land \text{Enters}(y) \land \neg \text{VIP}(y) \rightarrow \text{Searches}(x, y))$<br>
      $\implies \neg \text{Official}(x) \lor \neg \text{Enters}(y) \lor \text{VIP}(y) \lor \text{Searches}(x, y)$</li>
    <li>"Some drug smugglers entered the country and were only searched by drug smugglers."<br>
      $\exists y (\text{Smuggler}(y) \land \text{Enters}(y) \land \forall z (\text{Searches}(z, y) \rightarrow \text{Smuggler}(z)))$<br>
      $\implies \text{Smuggler}(A) \land \text{Enters}(A) \land (\neg \text{Searches}(z, A) \lor \text{Smuggler}(z))$ (Skolem constant $A$)</li>
    <li>"No drug smuggler is a VIP."<br>
      $\forall x (\text{Smuggler}(x) \rightarrow \neg \text{VIP}(x)) \implies \neg \text{Smuggler}(x) \lor \neg \text{VIP}(x)$</li>
  </ol>
  <p><strong>Query to Prove:</strong> "Some customs officials are drug smugglers." ($\exists x (\text{Official}(x) \land \text{Smuggler}(x))$)</p>
  <p><strong>Refutation:</strong> Negated Query: $\neg \exists x (\text{Official}(x) \land \text{Smuggler}(x)) \implies \forall x (\neg \text{Official}(x) \lor \neg \text{Smuggler}(x))$.</p>
  <p><strong>Resolution Steps:</strong></p>
  <ol>
    <li>Clause 3 with $\text{Smuggler}(A) \implies \mathbf{C_5: \neg \text{VIP}(A)}$.</li>
    <li>Clause 1 with $\{ y/A \} \implies \mathbf{C_6: \neg \text{Official}(x) \lor \text{VIP}(A) \lor \text{Searches}(x, A)}$.</li>
    <li>Resolve $C_6$ with $C_5 \implies \mathbf{C_7: \neg \text{Official}(x) \lor \text{Searches}(x, A)}$.</li>
    <li>Clause 2 (Searches part): $\neg \text{Searches}(z, A) \lor \text{Smuggler}(z)$. Resolve with $C_7 \{ z/x \} \implies \mathbf{C_8: \neg \text{Official}(x) \lor \text{Smuggler}(x)}$.</li>
    <li>Resolve $C_8$ with Negated Query clause $(\neg \text{Official}(x) \lor \neg \text{Smuggler}(x))$: If there exists any customs official $O_1 \implies \mathbf{\Box \text{ (CONTRADICTION)}}$.</li>
  </ol>
  $$\mathbf{\text{Q.E.D. Proven that some customs officials must be drug smugglers!}}$$
</div>
"""

# Extra depth for AI M4
M4_EXTRA = r"""
<h2 class="section-title">Topic 29.2: Advanced Bayesian Inference Algorithms & Markov Random Fields</h2>

<div class="formula-card">
  <strong>The d-Separation (Directed Separation) Triad Rules:</strong>
  Let $X, Y$ be nodes and $E$ be a set of observed evidence nodes in a DAG:
  1. <strong>Causal Chain ($X \rightarrow Z \rightarrow Y$):</strong> $X$ and $Y$ are conditionally independent given $Z$ ($Z \in E$).
  2. <strong>Common Cause / Fork ($X \leftarrow Z \rightarrow Y$):</strong> $X$ and $Y$ are conditionally independent given $Z$ ($Z \in E$).
  3. <strong>Common Effect / Collider / V-Structure ($X \rightarrow Z \leftarrow Y$):</strong> $X$ and $Y$ are <strong>DEPENDENT</strong> if $Z \in E$ (or any descendant of $Z \in E$)! (Known as <em>Explaining Away</em>).
</div>

<div class="worked-box">
  <div class="worked-title">🏛️ Step-by-Step Variable Elimination Algorithm Trace</div>
  <p>Compute query $P(B \mid J=t, M=t)$ using dynamic programming factor multiplication and summation:</p>
  $$\mathbf{P(B \mid j, m) = \alpha \sum_e \sum_a P(B) P(e) P(a \mid B, e) P(j \mid a) P(m \mid a)}$$
  <ol>
    <li>Create initial factors: $f_1(B) = P(B), \ f_2(E) = P(E), \ f_3(A, B, E) = P(A \mid B, E), \ f_4(A) = P(j \mid A), \ f_5(A) = P(m \mid A)$.</li>
    <li>Eliminate $E$: Multiply $f_2(E) \times f_3(A, B, E)$ and sum out $E \implies \mathbf{f_6(A, B) = \sum_e f_2(e) f_3(A, B, e)}$.</li>
    <li>Eliminate $A$: Multiply $f_4(A) \times f_5(A) \times f_6(A, B)$ and sum out $A \implies \mathbf{f_7(B) = \sum_a f_4(a) f_5(a) f_6(a, B)}$.</li>
    <li>Multiply remaining factor with prior: $f_8(B) = f_1(B) \times f_7(B)$.</li>
    <li>Normalize: $\alpha = \frac{1}{f_8(B=t) + f_8(B=f)} \implies \mathbf{P(B=t \mid j, m) \approx 0.284 = \mathbf{28.4\%}}$.</li>
  </ol>
</div>
"""

# Extra depth for AI M5
M5_EXTRA = r"""
<h2 class="section-title">Topic 38.2: Comprehensive Numerical Problem Bank in Machine Learning & Deep Learning</h2>

<div class="worked-box">
  <div class="worked-title">🏛️ Complete Step-by-Step Backpropagation Numerical Walkthrough</div>
  <p>Consider a 2-input, 2-hidden-neuron, 1-output-neuron neural network with Sigmoid activations:</p>
  <ul>
    <li>Inputs: $x_1 = 0.05, x_2 = 0.10$; Target Output: $y = 0.01$; Learning Rate: $\eta = 0.5$.</li>
    <li>Hidden Layer Weights: $w_1 = 0.15, w_2 = 0.20, w_3 = 0.25, w_4 = 0.30$; Biases: $b_1 = 0.35$.</li>
    <li>Output Layer Weights: $w_5 = 0.40, w_6 = 0.45$; Bias: $b_2 = 0.60$.</li>
  </ul>
  <p><strong>1. Forward Propagation Pass:</strong></p>
  $$z_{h1} = (0.05)(0.15) + (0.10)(0.20) + 0.35 = 0.0075 + 0.02 + 0.35 = 0.3775$$
  $$a_{h1} = \sigma(0.3775) = \frac{1}{1 + e^{-0.3775}} = \mathbf{0.593269992}$$
  $$z_{h2} = (0.05)(0.25) + (0.10)(0.30) + 0.35 = 0.0125 + 0.03 + 0.35 = 0.3925$$
  $$a_{h2} = \sigma(0.3925) = \frac{1}{1 + e^{-0.3925}} = \mathbf{0.596884378}$$
  $$z_{o1} = (0.593269992)(0.40) + (0.596884378)(0.45) + 0.60 = 0.237308 + 0.268598 + 0.60 = 1.105906$$
  $$\mathbf{a_{o1} = \sigma(1.105906) = \frac{1}{1 + e^{-1.105906}} = \mathbf{0.75136507}}$$
  $$\mathbf{\text{Total Squared Loss } E = \frac{1}{2} (y - a_{o1})^2 = \frac{1}{2} (0.01 - 0.751365)^2 = \mathbf{0.274811}}$$
  <p><strong>2. Backward Propagation Gradient & Weight Updates:</strong></p>
  $$\delta_{o1} = (y - a_{o1}) \cdot a_{o1}(1 - a_{o1}) = (0.01 - 0.751365) \times (0.751365)(1 - 0.751365) = -0.741365 \times 0.186815 = \mathbf{-0.138497}$$
  $$\frac{\partial E}{\partial w_5} = - \delta_{o1} \cdot a_{h1} = - (-0.138497) \times 0.59327 = \mathbf{+0.082166}$$
  $$\mathbf{w_5^{\text{new}} = w_5 - \eta \frac{\partial E}{\partial w_5} = 0.40 - 0.5(0.082166) = \mathbf{0.358917}}$$
  <p><em>Interpretation:</em> The output weight $w_5$ is decreased from $0.40$ to $0.3589$, reducing prediction error on the next iteration!</p>
</div>
"""

def expand_ai():
    with open(os.path.join(AI_DIR, "ai_module1_content.py"), "r", encoding="utf-8") as f:
        m1 = f.read()
    if "Topic 7.2: In-Depth PEAS" not in m1:
        m1 = m1.rstrip().rstrip('"""').rstrip() + M1_EXTRA + '\n"""\n'
        with open(os.path.join(AI_DIR, "ai_module1_content.py"), "w", encoding="utf-8") as f:
            f.write(m1)
        print("Expanded AI M1.")

    with open(os.path.join(AI_DIR, "ai_module2_content.py"), "r", encoding="utf-8") as f:
        m2 = f.read()
    if "Topic 13.2: Comprehensive Heuristic" not in m2:
        m2 = m2.rstrip().rstrip('"""').rstrip() + M2_EXTRA + '\n"""\n'
        with open(os.path.join(AI_DIR, "ai_module2_content.py"), "w", encoding="utf-8") as f:
            f.write(m2)
        print("Expanded AI M2.")

    with open(os.path.join(AI_DIR, "ai_module3_content.py"), "r", encoding="utf-8") as f:
        m3 = f.read()
    if "Topic 22.2: Advanced Knowledge" not in m3:
        m3 = m3.rstrip().rstrip('"""').rstrip() + M3_EXTRA + '\n"""\n'
        with open(os.path.join(AI_DIR, "ai_module3_content.py"), "w", encoding="utf-8") as f:
            f.write(m3)
        print("Expanded AI M3.")

    with open(os.path.join(AI_DIR, "ai_module4_content.py"), "r", encoding="utf-8") as f:
        m4 = f.read()
    if "Topic 29.2: Advanced Bayesian" not in m4:
        m4 = m4.rstrip().rstrip('"""').rstrip() + M4_EXTRA + '\n"""\n'
        with open(os.path.join(AI_DIR, "ai_module4_content.py"), "w", encoding="utf-8") as f:
            f.write(m4)
        print("Expanded AI M4.")

    with open(os.path.join(AI_DIR, "ai_module5_content.py"), "r", encoding="utf-8") as f:
        m5 = f.read()
    if "Topic 38.2: Comprehensive Numerical" not in m5:
        m5 = m5.rstrip().rstrip('"""').rstrip() + M5_EXTRA + '\n"""\n'
        with open(os.path.join(AI_DIR, "ai_module5_content.py"), "w", encoding="utf-8") as f:
            f.write(m5)
        print("Expanded AI M5.")

if __name__ == "__main__":
    expand_ai()
